import type {
  Conversation,
  Invoice,
  NegotiationMessage,
  Product,
  RestockRecommendation,
  Supplier,
  TimelineEvent,
  Workflow,
} from "@/lib/types"

export const mockSuppliers: Supplier[] = [
  {
    id: "sup-001",
    name: "Northstar Foods",
    region: "US West",
    reliabilityScore: 94,
    leadTimeDays: 5,
    status: "preferred",
  },
  {
    id: "sup-002",
    name: "Harbor Beverage Co.",
    region: "US Central",
    reliabilityScore: 79,
    leadTimeDays: 8,
    status: "watchlist",
  },
  {
    id: "sup-003",
    name: "Pacific Snacks Supply",
    region: "US West",
    reliabilityScore: 89,
    leadTimeDays: 4,
    status: "preferred",
  },
  {
    id: "sup-004",
    name: "Evergreen Household Goods",
    region: "US East",
    reliabilityScore: 86,
    leadTimeDays: 6,
    status: "preferred",
  },
]

export const mockProducts: Product[] = [
  {
    id: "prod-001",
    sku: "SKU-ALM-8842",
    name: "Almond Protein Bar 12ct",
    category: "Packaged Goods",
    stockOnHand: 418,
    reorderPoint: 360,
    staticThreshold: 360,
    aiThreshold: 520,
    unitCost: 18.4,
    maxStockAmount: 1500,
    forecastDemand: 680,
    monthlyVelocity: 1260,
    trend30d: -18,
    trend365d: 9,
    supplierId: "sup-001",
    conversationId: "conv-1001",
    invoiceId: "inv-7001",
    status: "near-threshold",
  },
  {
    id: "prod-002",
    sku: "SKU-CFE-1290",
    name: "Cold Brew Concentrate 1L",
    category: "Beverages",
    stockOnHand: 96,
    reorderPoint: 140,
    staticThreshold: 140,
    aiThreshold: 210,
    unitCost: 22.75,
    maxStockAmount: 640,
    forecastDemand: 380,
    monthlyVelocity: 840,
    trend30d: -31,
    trend365d: 22,
    supplierId: "sup-002",
    conversationId: "conv-1002",
    invoiceId: "inv-7002",
    status: "below-threshold",
  },
  {
    id: "prod-003",
    sku: "SKU-SNP-4471",
    name: "Sea Salt Plantain Chips",
    category: "Snacks",
    stockOnHand: 740,
    reorderPoint: 410,
    staticThreshold: 410,
    aiThreshold: 560,
    unitCost: 9.8,
    maxStockAmount: 1800,
    forecastDemand: 610,
    monthlyVelocity: 980,
    trend30d: 6,
    trend365d: 14,
    supplierId: "sup-003",
    conversationId: "conv-1003",
    invoiceId: "inv-7003",
    status: "healthy",
  },
  {
    id: "prod-004",
    sku: "SKU-LND-3021",
    name: "Citrus Laundry Sheets 60ct",
    category: "Household",
    stockOnHand: 188,
    reorderPoint: 220,
    staticThreshold: 220,
    aiThreshold: 330,
    unitCost: 12.35,
    maxStockAmount: 900,
    forecastDemand: 420,
    monthlyVelocity: 690,
    trend30d: -24,
    trend365d: 7,
    supplierId: "sup-004",
    conversationId: "conv-1004",
    invoiceId: "inv-7004",
    status: "batch-candidate",
  },
  {
    id: "prod-005",
    sku: "SKU-RCE-7740",
    name: "Jasmine Rice 5kg",
    category: "Pantry",
    stockOnHand: 58,
    reorderPoint: 120,
    staticThreshold: 120,
    aiThreshold: 180,
    unitCost: 16.1,
    maxStockAmount: 720,
    forecastDemand: 290,
    monthlyVelocity: 540,
    trend30d: -37,
    trend365d: 18,
    supplierId: "sup-001",
    conversationId: "conv-1005",
    invoiceId: "inv-7001",
    status: "below-threshold",
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "conv-1001",
    productSku: "SKU-ALM-8842",
    linkedSkus: ["SKU-ALM-8842", "SKU-RCE-7740"],
    supplierId: "sup-001",
    subject: "Expedite next protein bar shipment",
    source: "Email",
    negotiationState: "Counter Offer Suggested",
    latestMessage: "Can confirm 1,200 cases this week with revised payment terms.",
    targetPriceRange: "$17.90 - $18.25 per case",
    createdDate: "2026-04-18",
    status: "negotiating",
    priority: "high",
    lastMessageAt: "2026-04-19T06:40:00.000Z",
    aiExtraction: {
      extractedPrice: "$18.40 per case",
      extractedQuantity: "1,200 cases",
      deliveryEstimate: "Apr 24 - Apr 26",
      supplierLanguage: "English",
      detectedIntent: "Accept with payment term adjustment",
      missingFields: ["Freight surcharge confirmation"],
      confidenceScore: 91,
    },
    nextAction: {
      recommendedNextStep: "Generate counter offer with net-30 terms and bundled rice allocation.",
      negotiationSummary:
        "Supplier can meet quantity but wants adjusted payment terms. Batch with Jasmine Rice improves freight utilization.",
      linkedInvoiceStatus: "Waiting approval",
    },
  },
  {
    id: "conv-1002",
    productSku: "SKU-CFE-1290",
    linkedSkus: ["SKU-CFE-1290"],
    supplierId: "sup-002",
    subject: "Cold brew shortage and split delivery terms",
    source: "Chat App",
    negotiationState: "Needs Analysis",
    latestMessage: "Screenshot shows split shipment dates but no confirmed freight cap.",
    targetPriceRange: "$21.90 - $22.50 per unit",
    createdDate: "2026-04-19",
    status: "needs-reply",
    priority: "critical",
    lastMessageAt: "2026-04-19T05:55:00.000Z",
    aiExtraction: {
      extractedPrice: "$22.75 per unit",
      extractedQuantity: "480 units",
      deliveryEstimate: "Apr 23 and Apr 29 split",
      supplierLanguage: "English",
      detectedIntent: "Propose split delivery with price hold",
      missingFields: ["Freight cap", "Second shipment quantity"],
      confidenceScore: 88,
    },
    nextAction: {
      recommendedNextStep: "Request clarification on freight cap before accepting split shipment.",
      negotiationSummary:
        "Supplier is willing to split delivery, but invoice risk remains until freight terms are explicit.",
      linkedInvoiceStatus: "Needs review",
    },
  },
  {
    id: "conv-1003",
    productSku: "SKU-SNP-4471",
    linkedSkus: ["SKU-SNP-4471"],
    supplierId: "sup-003",
    subject: "Confirm promo month reserve allocation",
    source: "PDF",
    negotiationState: "Closed",
    latestMessage: "Promo reserve allocation confirmed and invoice packet completed.",
    targetPriceRange: "$9.40 - $9.75 per carton",
    createdDate: "2026-04-17",
    status: "resolved",
    priority: "medium",
    lastMessageAt: "2026-04-18T23:15:00.000Z",
    aiExtraction: {
      extractedPrice: "$9.80 per carton",
      extractedQuantity: "900 cartons",
      deliveryEstimate: "Week 46 reserve",
      supplierLanguage: "English",
      detectedIntent: "Reserve campaign allocation",
      missingFields: ["Final allocation date"],
      confidenceScore: 84,
    },
    nextAction: {
      recommendedNextStep: "Keep closed packet available for completed invoice history.",
      negotiationSummary:
        "Supplier allocation, invoice validation, and settlement packet are complete.",
      linkedInvoiceStatus: "Completed",
    },
  },
  {
    id: "conv-1004",
    productSku: "SKU-LND-3021",
    linkedSkus: ["SKU-LND-3021"],
    supplierId: "sup-004",
    subject: "Laundry sheets MOQ adjustment",
    source: "Image",
    negotiationState: "Accepted",
    latestMessage: "Image of updated MOQ sheet accepted for exception approval.",
    targetPriceRange: "$12.00 - $12.40 per pack",
    createdDate: "2026-04-16",
    status: "resolved",
    priority: "low",
    lastMessageAt: "2026-04-18T17:20:00.000Z",
    aiExtraction: {
      extractedPrice: "$12.35 per pack",
      extractedQuantity: "620 packs",
      deliveryEstimate: "Apr 28",
      supplierLanguage: "English",
      detectedIntent: "Accept MOQ exception",
      missingFields: [],
      confidenceScore: 96,
    },
    nextAction: {
      recommendedNextStep: "Attach accepted MOQ sheet to invoice exception packet.",
      negotiationSummary:
        "MOQ adjustment is accepted and ready to unblock the invoice management workflow.",
      linkedInvoiceStatus: "Blocked",
    },
  },
  {
    id: "conv-1005",
    productSku: "SKU-RCE-7740",
    linkedSkus: ["SKU-RCE-7740", "SKU-ALM-8842"],
    supplierId: "sup-001",
    subject: "Voice note: rice reorder bundle",
    source: "Voice Note",
    negotiationState: "Escalated",
    latestMessage: "Voice note suggests a rice bundle, but quantity and delivery date conflict.",
    targetPriceRange: "$15.80 - $16.25 per bag",
    createdDate: "2026-04-19",
    status: "needs-reply",
    priority: "critical",
    lastMessageAt: "2026-04-19T08:10:00.000Z",
    aiExtraction: {
      extractedPrice: "$16.10 per bag",
      extractedQuantity: "700 bags",
      deliveryEstimate: "Apr 25 or Apr 30",
      supplierLanguage: "English voice note",
      detectedIntent: "Bundle rice with protein bar shipment",
      missingFields: ["Confirmed delivery date", "Bundle discount"],
      confidenceScore: 79,
    },
    nextAction: {
      recommendedNextStep: "Request clarification and escalate if supplier cannot lock date today.",
      negotiationSummary:
        "The same-supplier bundle is attractive, but messy voice input contains conflicting dates.",
      linkedInvoiceStatus: "Waiting approval",
    },
  },
]

export const mockNegotiationMessages: NegotiationMessage[] = [
  {
    id: "msg-001",
    conversationId: "conv-1002",
    supplierId: "sup-002",
    type: "ai-interpretation",
    author: "ai",
    body: "Suggested counteroffer keeps unit cost flat if delivery moves to a split shipment.",
    sentiment: "positive",
    createdAt: "2026-04-19T05:55:00.000Z",
    attachmentType: "screenshot",
    attachmentLabel: "chat-screenshot-apr19.png",
  },
  {
    id: "msg-002",
    conversationId: "conv-1001",
    supplierId: "sup-001",
    type: "supplier-message",
    author: "supplier",
    body: "Can confirm 1,200 cases this week with revised payment terms.",
    sentiment: "neutral",
    createdAt: "2026-04-19T03:30:00.000Z",
    attachmentType: "email",
    attachmentLabel: "Email thread from Northstar Foods",
  },
  {
    id: "msg-003",
    conversationId: "conv-1003",
    supplierId: "sup-003",
    type: "merchant-action",
    author: "merchant",
    body: "Please reserve the promo allocation for week 46 before the 11.11 campaign.",
    sentiment: "neutral",
    createdAt: "2026-04-18T23:15:00.000Z",
    attachmentType: "pdf",
    attachmentLabel: "promo-reserve-allocation.pdf",
  },
  {
    id: "msg-004",
    conversationId: "conv-1002",
    supplierId: "sup-002",
    type: "supplier-message",
    author: "supplier",
    body: "We can split delivery: first truck Apr 23, second truck likely Apr 29. Freight depends on final route.",
    sentiment: "risk",
    createdAt: "2026-04-19T05:44:00.000Z",
    attachmentType: "image",
    attachmentLabel: "route-board-photo.jpg",
  },
  {
    id: "msg-005",
    conversationId: "conv-1002",
    supplierId: "sup-002",
    type: "ai-recommendation",
    author: "ai",
    body: "Request freight cap and second shipment quantity before accepting. Current invoice exposure is not bounded.",
    sentiment: "risk",
    createdAt: "2026-04-19T05:58:00.000Z",
  },
  {
    id: "msg-006",
    conversationId: "conv-1004",
    supplierId: "sup-004",
    type: "supplier-message",
    author: "supplier",
    body: "Uploaded MOQ sheet shows 620 pack exception approved by regional sales.",
    sentiment: "positive",
    createdAt: "2026-04-18T17:20:00.000Z",
    attachmentType: "image",
    attachmentLabel: "moq-exception-sheet.jpg",
  },
  {
    id: "msg-007",
    conversationId: "conv-1005",
    supplierId: "sup-001",
    type: "supplier-message",
    author: "supplier",
    body: "Voice note transcription: We can add rice to the protein bar truck, maybe Apr 25, maybe Apr 30, price stays sixteen ten if full pallet.",
    sentiment: "risk",
    createdAt: "2026-04-19T08:10:00.000Z",
    attachmentType: "voice",
    attachmentLabel: "rice-bundle-voice-note.m4a",
  },
  {
    id: "msg-008",
    conversationId: "conv-1005",
    supplierId: "sup-001",
    type: "ai-interpretation",
    author: "ai",
    body: "AI detected conflicting delivery dates and a conditional full-pallet price. Bundle discount is missing.",
    sentiment: "risk",
    createdAt: "2026-04-19T08:12:00.000Z",
  },
]

export const mockInvoices: Invoice[] = [
  {
    id: "inv-7001",
    supplierId: "sup-001",
    productSku: "SKU-ALM-8842",
    linkedSkus: ["SKU-ALM-8842", "SKU-RCE-7740"],
    workflowId: "wf-1002",
    invoiceNumber: "NSF-48291",
    amount: 48240,
    negotiatedAmount: 48000,
    expectedQuantity: 1200,
    invoiceQuantity: 1200,
    unitPrice: 40.2,
    subtotal: 48240,
    currency: "USD",
    risk: "waiting approval",
    riskLevel: "Low Risk",
    riskReason: "Amount variance is within tolerance and supplier identity matches.",
    validationStatus: "Validated",
    approvalState: "Waiting Approval",
    sourceType: "PDF",
    fileName: "NSF-48291-april-replenishment.pdf",
    fileSize: "248 KB",
    bankDetails: "Chase **** 4412",
    paymentTerms: "Net 30",
    riskConfidence: 93,
    flags: {
      bankDetailsIssue: false,
      amountMismatch: false,
      missingFields: false,
      supplierInconsistency: false,
    },
    mismatches: [],
    history: [
      {
        timestamp: "2026-04-19T07:20:00.000Z",
        title: "Invoice parsed",
        description: "Z.AI extracted line items and supplier remittance details.",
      },
      {
        timestamp: "2026-04-19T07:28:00.000Z",
        title: "Validation passed",
        description: "Matched against negotiated quantity and supplier profile.",
      },
    ],
    notes: "Safe to approve after merchant confirms restock packet.",
    status: "pending",
    dueDate: "2026-04-27",
    lastUpdated: "2026-04-19T07:28:00.000Z",
  },
  {
    id: "inv-7002",
    supplierId: "sup-002",
    productSku: "SKU-CFE-1290",
    linkedSkus: ["SKU-CFE-1290"],
    workflowId: "wf-1003",
    invoiceNumber: "HBC-18044",
    amount: 19780,
    negotiatedAmount: 18400,
    expectedQuantity: 480,
    invoiceQuantity: 480,
    unitPrice: 41.21,
    subtotal: 19780,
    currency: "USD",
    risk: "needs review",
    riskLevel: "High Risk",
    riskReason: "Freight charge is not capped and total exceeds negotiated amount.",
    validationStatus: "Mismatch Detected",
    approvalState: "Needs Review",
    sourceType: "Email Attachment",
    fileName: "HBC-18044-split-shipment.pdf",
    fileSize: "312 KB",
    bankDetails: "Wells Fargo **** 9088",
    paymentTerms: "Net 15",
    riskConfidence: 89,
    flags: {
      bankDetailsIssue: false,
      amountMismatch: true,
      missingFields: true,
      supplierInconsistency: false,
    },
    mismatches: [
      "Invoice total exceeds negotiated amount by $1,380",
      "Freight cap missing from supplier conversation",
    ],
    history: [
      {
        timestamp: "2026-04-19T05:55:00.000Z",
        title: "Invoice parsed",
        description: "Split shipment invoice attached from supplier chat follow-up.",
      },
      {
        timestamp: "2026-04-19T06:04:00.000Z",
        title: "Mismatch detected",
        description: "Freight and total amount require review before approval.",
      },
    ],
    notes: "Hold until Harbor Beverage confirms freight cap.",
    status: "exception",
    dueDate: "2026-04-24",
    lastUpdated: "2026-04-19T06:04:00.000Z",
  },
  {
    id: "inv-7003",
    supplierId: "sup-003",
    productSku: "SKU-SNP-4471",
    linkedSkus: ["SKU-SNP-4471"],
    workflowId: "wf-1001",
    invoiceNumber: "PSS-92018",
    amount: 12860,
    negotiatedAmount: 12860,
    expectedQuantity: 900,
    invoiceQuantity: 900,
    unitPrice: 14.29,
    subtotal: 12860,
    currency: "USD",
    risk: "low risk",
    riskLevel: "Low Risk",
    riskReason: "Invoice matches expected allocation and bank details are verified.",
    validationStatus: "Validated",
    approvalState: "Completed",
    sourceType: "PDF",
    fileName: "PSS-92018-promo-reserve.pdf",
    fileSize: "190 KB",
    bankDetails: "Bank of America **** 1180",
    paymentTerms: "Net 30",
    riskConfidence: 97,
    flags: {
      bankDetailsIssue: false,
      amountMismatch: false,
      missingFields: false,
      supplierInconsistency: false,
    },
    mismatches: [],
    history: [
      {
        timestamp: "2026-04-18T22:45:00.000Z",
        title: "Invoice matched",
        description: "Validated against promo reserve allocation.",
      },
      {
        timestamp: "2026-04-19T01:10:00.000Z",
        title: "Marked completed",
        description: "Settlement packet closed.",
      },
    ],
    notes: "Completed and archived.",
    status: "paid",
    dueDate: "2026-05-02",
    lastUpdated: "2026-04-19T01:10:00.000Z",
  },
  {
    id: "inv-7004",
    supplierId: "sup-004",
    productSku: "SKU-LND-3021",
    linkedSkus: ["SKU-LND-3021"],
    workflowId: "wf-1003",
    invoiceNumber: "EHG-55107",
    amount: 22110,
    negotiatedAmount: 21000,
    expectedQuantity: 620,
    invoiceQuantity: 620,
    unitPrice: 35.66,
    subtotal: 22110,
    currency: "USD",
    risk: "blocked",
    riskLevel: "Medium Risk",
    riskReason: "MOQ exception accepted, but remittance details differ from supplier master.",
    validationStatus: "Missing Information",
    approvalState: "Blocked",
    sourceType: "Image",
    fileName: "EHG-55107-moq-sheet.jpg",
    fileSize: "1.1 MB",
    bankDetails: "Unverified account ending 3301",
    paymentTerms: "Due on receipt",
    riskConfidence: 82,
    flags: {
      bankDetailsIssue: true,
      amountMismatch: true,
      missingFields: true,
      supplierInconsistency: false,
    },
    mismatches: [
      "Bank details differ from supplier master",
      "Payment terms differ from accepted MOQ exception",
      "Subtotal exceeds negotiated amount by $1,110",
    ],
    history: [
      {
        timestamp: "2026-04-18T17:20:00.000Z",
        title: "Image invoice uploaded",
        description: "Supplier sent invoice image with MOQ sheet.",
      },
      {
        timestamp: "2026-04-18T17:44:00.000Z",
        title: "Blocked",
        description: "Remittance and payment terms require finance review.",
      },
    ],
    notes: "Do not approve until bank details are verified.",
    status: "blocked",
    dueDate: "2026-04-22",
    lastUpdated: "2026-04-18T17:44:00.000Z",
  },
]

export const mockWorkflows: Workflow[] = [
  {
    id: "wf-1001",
    title: "Promo reserve settlement review",
    stage: "ready for approval",
    status: "active",
    owner: "Nadia Chen",
    updatedAt: "2026-04-19T07:20:00.000Z",
  },
  {
    id: "wf-1002",
    title: "Northstar bundled replenishment",
    stage: "negotiation active",
    status: "blocked",
    owner: "Marcus Bell",
    updatedAt: "2026-04-19T06:05:00.000Z",
  },
  {
    id: "wf-1003",
    title: "April invoice exception review",
    stage: "invoice review",
    status: "pending",
    owner: "Priya Raman",
    updatedAt: "2026-04-18T22:45:00.000Z",
  },
]

export const dashboardKpis = [
  {
    title: "Low Stock Alerts",
    value: "4",
    change: "2 below AI threshold",
    tone: "warning" as const,
  },
  {
    title: "AI Threshold Changes Today",
    value: "3",
    change: "Cold brew, rice, protein bars",
    tone: "ai" as const,
  },
  {
    title: "Open Conversations",
    value: "5",
    change: "2 need operator review",
    tone: "default" as const,
  },
  {
    title: "Invoices Waiting Approval",
    value: "1",
    change: "$48.2K pending",
    tone: "danger" as const,
  },
]

export const stockTrendData = [
  {
    date: "Apr 01",
    proteinBars: 720,
    proteinThreshold: 470,
    coldBrew: 310,
    coldBrewThreshold: 180,
    rice: 230,
    riceThreshold: 160,
  },
  {
    date: "Apr 04",
    proteinBars: 660,
    proteinThreshold: 480,
    coldBrew: 252,
    coldBrewThreshold: 188,
    rice: 198,
    riceThreshold: 165,
  },
  {
    date: "Apr 07",
    proteinBars: 612,
    proteinThreshold: 490,
    coldBrew: 220,
    coldBrewThreshold: 196,
    rice: 146,
    riceThreshold: 170,
  },
  {
    date: "Apr 10",
    proteinBars: 560,
    proteinThreshold: 505,
    coldBrew: 174,
    coldBrewThreshold: 204,
    rice: 121,
    riceThreshold: 175,
  },
  {
    date: "Apr 13",
    proteinBars: 505,
    proteinThreshold: 515,
    coldBrew: 138,
    coldBrewThreshold: 208,
    rice: 88,
    riceThreshold: 178,
  },
  {
    date: "Apr 16",
    proteinBars: 462,
    proteinThreshold: 520,
    coldBrew: 112,
    coldBrewThreshold: 210,
    rice: 70,
    riceThreshold: 180,
  },
  {
    date: "Apr 19",
    proteinBars: 418,
    proteinThreshold: 520,
    coldBrew: 96,
    coldBrewThreshold: 210,
    rice: 58,
    riceThreshold: 180,
  },
]

export const monthlyDemandData = [
  { month: "Jan", demand: 8400, promo: "Baseline" },
  { month: "Feb", demand: 9100, promo: "Payday Sale" },
  { month: "Mar", demand: 12600, promo: "Raya" },
  { month: "Apr", demand: 9800, promo: "Baseline" },
  { month: "May", demand: 10400, promo: "Baseline" },
  { month: "Jun", demand: 11200, promo: "Payday Sale" },
  { month: "Jul", demand: 10100, promo: "Baseline" },
  { month: "Aug", demand: 10900, promo: "Baseline" },
  { month: "Sep", demand: 11800, promo: "Payday Sale" },
  { month: "Oct", demand: 12100, promo: "Baseline" },
  { month: "Nov", demand: 15800, promo: "11.11" },
  { month: "Dec", demand: 13900, promo: "Holiday" },
]

export const workflowStatusDistribution = [
  { name: "Review needed", value: 9, color: "#F59E0B" },
  { name: "Negotiation active", value: 7, color: "#8B5CF6" },
  { name: "Invoice review", value: 5, color: "#3B82F6" },
  { name: "Ready for approval", value: 6, color: "#10B981" },
  { name: "Blocked", value: 3, color: "#EF4444" },
  { name: "Completed", value: 18, color: "#6B7280" },
]

export const invoiceRiskDistribution = [
  { name: "Low risk", count: 2, color: "#10B981" },
  { name: "Waiting approval", count: 1, color: "#3B82F6" },
  { name: "Needs review", count: 1, color: "#F59E0B" },
  { name: "Blocked", count: 1, color: "#EF4444" },
  { name: "Completed", count: 1, color: "#6B7280" },
]

export const attentionItems = [
  {
    sku: "SKU-CFE-1290",
    productName: "Cold Brew Concentrate 1L",
    supplier: "Harbor Beverage Co.",
    currentStock: 96,
    aiThreshold: 210,
    conversationStatus: "needs reply",
    invoiceStatus: "needs review",
    priority: "critical",
    action: "Auto Restock",
    href: "/conversations/conv-1002",
  },
  {
    sku: "SKU-RCE-7740",
    productName: "Jasmine Rice 5kg",
    supplier: "Northstar Foods",
    currentStock: 58,
    aiThreshold: 180,
    conversationStatus: "negotiating",
    invoiceStatus: "waiting approval",
    priority: "critical",
    action: "Auto Restock",
    href: "/conversations/conv-1005",
  },
  {
    sku: "SKU-ALM-8842",
    productName: "Almond Protein Bar 12ct",
    supplier: "Northstar Foods",
    currentStock: 418,
    aiThreshold: 520,
    conversationStatus: "negotiating",
    invoiceStatus: "waiting approval",
    priority: "high",
    action: "Auto Restock",
    href: "/conversations/conv-1001",
  },
  {
    sku: "SKU-LND-3021",
    productName: "Citrus Laundry Sheets 60ct",
    supplier: "Evergreen Household Goods",
    currentStock: 188,
    aiThreshold: 330,
    conversationStatus: "resolved",
    invoiceStatus: "blocked",
    priority: "high",
    action: "Unblock",
    href: "/invoice-management/inv-7004",
  },
]

export const insightCards = {
  thresholdRecommendation: {
    title: "AI Threshold Recommendation",
    value: "+18%",
    body: "Raise cold brew threshold from 178 to 210 units through May due to promo uplift and slower supplier lead time.",
  },
  recentSupplierActivity: [
    "Harbor Beverage proposed split shipment for Apr 23 and Apr 29.",
    "Northstar Foods accepted expedited protein bar quantity.",
    "Evergreen Household Goods requested MOQ exception approval.",
  ],
  approvalQueueSummary: {
    invoices: 1,
    thresholdChanges: 3,
    replenishmentOrders: 3,
  },
}

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: "evt-001",
    workflowId: "wf-1001",
    title: "Approval packet generated",
    description: "Z.AI assembled demand forecast, supplier terms, and invoice references.",
    timestamp: "2026-04-19T07:20:00.000Z",
    tone: "ai",
  },
  {
    id: "evt-002",
    workflowId: "wf-1002",
    title: "Supplier counteroffer flagged",
    description: "Pricing moved above tolerance and requires merchant review.",
    timestamp: "2026-04-19T06:05:00.000Z",
    tone: "warning",
  },
  {
    id: "evt-003",
    workflowId: "wf-1003",
    title: "Invoice variance detected",
    description: "Harbor Beverage invoice differs from expected freight charge.",
    timestamp: "2026-04-18T22:45:00.000Z",
    tone: "danger",
  },
  {
    id: "evt-004",
    workflowId: "wf-1001",
    title: "Threshold change queued",
    description: "Cold brew AI threshold increased for upcoming Payday Sale demand.",
    timestamp: "2026-04-18T18:10:00.000Z",
    tone: "ai",
  },
]

export const topSuppliersSummary = [
  {
    supplier: "Northstar Foods",
    openOrders: 8,
    reliability: 94,
    invoiceExposure: "$82.4K",
    tone: "success" as const,
  },
  {
    supplier: "Pacific Snacks Supply",
    openOrders: 5,
    reliability: 89,
    invoiceExposure: "$31.8K",
    tone: "success" as const,
  },
  {
    supplier: "Harbor Beverage Co.",
    openOrders: 6,
    reliability: 79,
    invoiceExposure: "$46.2K",
    tone: "warning" as const,
  },
]

export const inventorySummaryStats = [
  {
    title: "Total Active SKUs",
    value: "5",
    change: "4 suppliers tracked",
    tone: "default" as const,
  },
  {
    title: "Near Threshold",
    value: "1",
    change: "Protein bars",
    tone: "warning" as const,
  },
  {
    title: "Below Threshold",
    value: "2",
    change: "Requires restock",
    tone: "danger" as const,
  },
  {
    title: "Batch Restock Candidates",
    value: "1",
    change: "Same-supplier bundle",
    tone: "ai" as const,
  },
]

export const inventoryHealthDistribution = [
  { name: "Healthy", count: 1, color: "#10B981" },
  { name: "Near Threshold", count: 1, color: "#F59E0B" },
  { name: "Below Threshold", count: 2, color: "#EF4444" },
  { name: "Batch Candidate", count: 1, color: "#8B5CF6" },
]

export const supplierExposureData = [
  { supplier: "Northstar Foods", products: 2, color: "#3B82F6" },
  { supplier: "Harbor Beverage Co.", products: 1, color: "#F59E0B" },
  { supplier: "Pacific Snacks Supply", products: 1, color: "#10B981" },
  { supplier: "Evergreen Household Goods", products: 1, color: "#8B5CF6" },
]

export const productStockDemandTrendBySku = {
  "SKU-ALM-8842": [
    { month: "May", stock: 1120, demand: 780, promotion: "" },
    { month: "Jun", stock: 1010, demand: 820, promotion: "Payday Sale" },
    { month: "Jul", stock: 940, demand: 760, promotion: "" },
    { month: "Aug", stock: 880, demand: 790, promotion: "" },
    { month: "Sep", stock: 760, demand: 840, promotion: "Payday Sale" },
    { month: "Oct", stock: 690, demand: 870, promotion: "" },
    { month: "Nov", stock: 560, demand: 1180, promotion: "11.11" },
    { month: "Dec", stock: 780, demand: 960, promotion: "Holiday" },
    { month: "Jan", stock: 650, demand: 820, promotion: "" },
    { month: "Feb", stock: 590, demand: 850, promotion: "Payday Sale" },
    { month: "Mar", stock: 505, demand: 940, promotion: "Raya" },
    { month: "Apr", stock: 418, demand: 680, promotion: "" },
  ],
  "SKU-CFE-1290": [
    { month: "May", stock: 420, demand: 310, promotion: "" },
    { month: "Jun", stock: 360, demand: 350, promotion: "Payday Sale" },
    { month: "Jul", stock: 330, demand: 330, promotion: "" },
    { month: "Aug", stock: 292, demand: 360, promotion: "" },
    { month: "Sep", stock: 248, demand: 410, promotion: "Payday Sale" },
    { month: "Oct", stock: 218, demand: 390, promotion: "" },
    { month: "Nov", stock: 176, demand: 520, promotion: "11.11" },
    { month: "Dec", stock: 268, demand: 470, promotion: "Holiday" },
    { month: "Jan", stock: 212, demand: 360, promotion: "" },
    { month: "Feb", stock: 174, demand: 400, promotion: "Payday Sale" },
    { month: "Mar", stock: 132, demand: 430, promotion: "Raya" },
    { month: "Apr", stock: 96, demand: 380, promotion: "" },
  ],
  "SKU-SNP-4471": [
    { month: "May", stock: 1040, demand: 680, promotion: "" },
    { month: "Jun", stock: 990, demand: 720, promotion: "Payday Sale" },
    { month: "Jul", stock: 930, demand: 690, promotion: "" },
    { month: "Aug", stock: 900, demand: 700, promotion: "" },
    { month: "Sep", stock: 860, demand: 750, promotion: "Payday Sale" },
    { month: "Oct", stock: 810, demand: 730, promotion: "" },
    { month: "Nov", stock: 760, demand: 980, promotion: "11.11" },
    { month: "Dec", stock: 910, demand: 880, promotion: "Holiday" },
    { month: "Jan", stock: 840, demand: 710, promotion: "" },
    { month: "Feb", stock: 805, demand: 735, promotion: "Payday Sale" },
    { month: "Mar", stock: 770, demand: 760, promotion: "Raya" },
    { month: "Apr", stock: 740, demand: 610, promotion: "" },
  ],
  "SKU-LND-3021": [
    { month: "May", stock: 620, demand: 330, promotion: "" },
    { month: "Jun", stock: 560, demand: 360, promotion: "Payday Sale" },
    { month: "Jul", stock: 510, demand: 350, promotion: "" },
    { month: "Aug", stock: 475, demand: 365, promotion: "" },
    { month: "Sep", stock: 414, demand: 390, promotion: "Payday Sale" },
    { month: "Oct", stock: 380, demand: 370, promotion: "" },
    { month: "Nov", stock: 318, demand: 470, promotion: "11.11" },
    { month: "Dec", stock: 400, demand: 430, promotion: "Holiday" },
    { month: "Jan", stock: 342, demand: 360, promotion: "" },
    { month: "Feb", stock: 300, demand: 395, promotion: "Payday Sale" },
    { month: "Mar", stock: 242, demand: 450, promotion: "Raya" },
    { month: "Apr", stock: 188, demand: 420, promotion: "" },
  ],
  "SKU-RCE-7740": [
    { month: "May", stock: 390, demand: 240, promotion: "" },
    { month: "Jun", stock: 336, demand: 260, promotion: "Payday Sale" },
    { month: "Jul", stock: 300, demand: 250, promotion: "" },
    { month: "Aug", stock: 270, demand: 265, promotion: "" },
    { month: "Sep", stock: 228, demand: 290, promotion: "Payday Sale" },
    { month: "Oct", stock: 190, demand: 275, promotion: "" },
    { month: "Nov", stock: 144, demand: 360, promotion: "11.11" },
    { month: "Dec", stock: 210, demand: 330, promotion: "Holiday" },
    { month: "Jan", stock: 164, demand: 270, promotion: "" },
    { month: "Feb", stock: 122, demand: 295, promotion: "Payday Sale" },
    { month: "Mar", stock: 86, demand: 335, promotion: "Raya" },
    { month: "Apr", stock: 58, demand: 290, promotion: "" },
  ],
}

export const productMonthlySummaryBySku = {
  "SKU-ALM-8842": [
    { month: "Jan", averageSales: 820, seasonalSpike: "Normal", promotionNote: "Baseline demand" },
    { month: "Feb", averageSales: 850, seasonalSpike: "Medium", promotionNote: "Payday Sale lift" },
    { month: "Mar", averageSales: 940, seasonalSpike: "High", promotionNote: "Raya pantry bundle" },
    { month: "Apr", averageSales: 680, seasonalSpike: "Normal", promotionNote: "Replenishment lag" },
  ],
  "SKU-CFE-1290": [
    { month: "Jan", averageSales: 360, seasonalSpike: "Normal", promotionNote: "Baseline demand" },
    { month: "Feb", averageSales: 400, seasonalSpike: "Medium", promotionNote: "Payday Sale lift" },
    { month: "Mar", averageSales: 430, seasonalSpike: "High", promotionNote: "Raya beverage bundle" },
    { month: "Apr", averageSales: 380, seasonalSpike: "High", promotionNote: "Supplier split delivery risk" },
  ],
  "SKU-SNP-4471": [
    { month: "Jan", averageSales: 710, seasonalSpike: "Normal", promotionNote: "Baseline demand" },
    { month: "Feb", averageSales: 735, seasonalSpike: "Medium", promotionNote: "Payday Sale lift" },
    { month: "Mar", averageSales: 760, seasonalSpike: "Medium", promotionNote: "Raya snack display" },
    { month: "Apr", averageSales: 610, seasonalSpike: "Normal", promotionNote: "Healthy stock cover" },
  ],
  "SKU-LND-3021": [
    { month: "Jan", averageSales: 360, seasonalSpike: "Normal", promotionNote: "Baseline demand" },
    { month: "Feb", averageSales: 395, seasonalSpike: "Medium", promotionNote: "Payday Sale lift" },
    { month: "Mar", averageSales: 450, seasonalSpike: "High", promotionNote: "Raya household refresh" },
    { month: "Apr", averageSales: 420, seasonalSpike: "Medium", promotionNote: "Bundle with same supplier" },
  ],
  "SKU-RCE-7740": [
    { month: "Jan", averageSales: 270, seasonalSpike: "Normal", promotionNote: "Baseline demand" },
    { month: "Feb", averageSales: 295, seasonalSpike: "Medium", promotionNote: "Payday Sale lift" },
    { month: "Mar", averageSales: 335, seasonalSpike: "High", promotionNote: "Raya pantry spike" },
    { month: "Apr", averageSales: 290, seasonalSpike: "High", promotionNote: "Below AI threshold" },
  ],
}

export const aiThresholdAnalysisBySku = {
  "SKU-ALM-8842": {
    currentThreshold: 520,
    recommendedThreshold: 610,
    safetyBuffer: "15 days",
    reorderUrgency: "High",
    confidenceScore: 91,
    explanation:
      "Demand is trending above static threshold and supplier lead time is stable, so Z.AI recommends lifting the reorder threshold before the next Payday Sale.",
  },
  "SKU-CFE-1290": {
    currentThreshold: 210,
    recommendedThreshold: 260,
    safetyBuffer: "10 days",
    reorderUrgency: "Critical",
    confidenceScore: 94,
    explanation:
      "Current stock is below AI threshold while demand remains elevated. Split delivery terms increase risk, so immediate supplier conversation is recommended.",
  },
  "SKU-SNP-4471": {
    currentThreshold: 560,
    recommendedThreshold: 540,
    safetyBuffer: "24 days",
    reorderUrgency: "Low",
    confidenceScore: 87,
    explanation:
      "Stock remains healthy against forecast demand. Z.AI recommends only a small reserve adjustment for the next promotion cycle.",
  },
  "SKU-LND-3021": {
    currentThreshold: 330,
    recommendedThreshold: 390,
    safetyBuffer: "12 days",
    reorderUrgency: "High",
    confidenceScore: 89,
    explanation:
      "Stock is under AI threshold and shares supplier capacity with other household goods, making this a strong batch restock candidate.",
  },
  "SKU-RCE-7740": {
    currentThreshold: 180,
    recommendedThreshold: 240,
    safetyBuffer: "8 days",
    reorderUrgency: "Critical",
    confidenceScore: 93,
    explanation:
      "Stock is well below AI threshold with seasonal pantry demand still elevated after Raya. Z.AI recommends bundling with Northstar Foods items.",
  },
}

export const supplierBatchAdvantageNotes = {
  "sup-001":
    "Combining pantry and packaged goods improves pallet utilization and reduces landed freight cost by an estimated 7%.",
  "sup-002":
    "Batching is limited by beverage lead time, but split delivery can protect service level for fast-moving SKUs.",
  "sup-003":
    "Supplier has healthy availability, so bundle only if promotion reserve needs to be secured early.",
  "sup-004":
    "Household goods can be bundled under the same MOQ exception to reduce approval cycles.",
}

export const restockRecommendations: RestockRecommendation[] = [
  {
    id: "restock-1002",
    sku: "SKU-CFE-1290",
    productName: "Cold Brew Concentrate 1L",
    supplier: "Harbor Beverage Co.",
    reason: "Current stock is below the AI threshold and 30D demand is declining stock coverage faster than lead time can recover.",
    currentStock: 96,
    aiThreshold: 210,
    targetPrice: "$21.90 - $22.50 per unit",
    quantity: 480,
    estimatedSpend: "$10.8K",
    conversationId: "conv-1002",
    automationPlan: [
      "Open supplier negotiation with target price and freight cap",
      "Confirm split delivery dates and shipment quantities",
      "Create replenishment order after supplier confirms terms",
      "Route invoice for exception review only if freight exceeds cap",
    ],
  },
  {
    id: "restock-1005",
    sku: "SKU-RCE-7740",
    productName: "Jasmine Rice 5kg",
    supplier: "Northstar Foods",
    reason: "Stock is critically below AI threshold and can be bundled with protein bars for better pallet utilization.",
    currentStock: 58,
    aiThreshold: 180,
    targetPrice: "$15.80 - $16.25 per bag",
    quantity: 700,
    estimatedSpend: "$11.3K",
    conversationId: "conv-1005",
    automationPlan: [
      "Bundle rice with Northstar Foods protein bar shipment",
      "Negotiate delivery date conflict from voice note",
      "Lock full-pallet price if bundle discount is confirmed",
      "Generate purchase order and keep merchant notified",
    ],
  },
  {
    id: "restock-1001",
    sku: "SKU-ALM-8842",
    productName: "Almond Protein Bar 12ct",
    supplier: "Northstar Foods",
    reason: "Stock is approaching the AI threshold before Payday Sale uplift.",
    currentStock: 418,
    aiThreshold: 520,
    targetPrice: "$17.90 - $18.25 per case",
    quantity: 1200,
    estimatedSpend: "$21.9K",
    conversationId: "conv-1001",
    automationPlan: [
      "Negotiate expedited quantity with existing supplier thread",
      "Hold target case price under AI threshold recommendation",
      "Bundle freight with Jasmine Rice if supplier confirms pallet space",
      "Prepare order packet for autonomous procurement tracking",
    ],
  },
]

export const invoiceSummaryStats = [
  {
    title: "Waiting Approval",
    value: "1",
    change: "$48.2K ready",
    tone: "ai" as const,
  },
  {
    title: "Needs Review",
    value: "1",
    change: "Amount mismatch",
    tone: "warning" as const,
  },
  {
    title: "Blocked",
    value: "1",
    change: "Bank details issue",
    tone: "danger" as const,
  },
  {
    title: "Completed",
    value: "1",
    change: "$12.9K closed",
    tone: "success" as const,
  },
]

export const invoiceRiskLevelDistribution = [
  { name: "Low Risk", count: 2, color: "#10B981" },
  { name: "Medium Risk", count: 1, color: "#F59E0B" },
  { name: "High Risk", count: 1, color: "#EF4444" },
]

export const approvalPipelineDistribution = [
  { name: "Waiting Approval", count: 1, color: "#3B82F6" },
  { name: "Needs Review", count: 1, color: "#F59E0B" },
  { name: "Blocked", count: 1, color: "#EF4444" },
  { name: "Completed", count: 1, color: "#10B981" },
]

export const supplierInvoiceVolume = [
  { supplier: "Northstar Foods", invoices: 1, color: "#3B82F6" },
  { supplier: "Harbor Beverage Co.", invoices: 1, color: "#F59E0B" },
  { supplier: "Pacific Snacks Supply", invoices: 1, color: "#10B981" },
  { supplier: "Evergreen Household Goods", invoices: 1, color: "#8B5CF6" },
]
